use crate::legacy_job_projection::Verdict;

pub(crate) struct Case {
    pub(crate) id: &'static str,
    pub(crate) args: &'static [&'static str],
    pub(crate) verdict: Verdict,
    pub(crate) reason: &'static str,
}

pub(crate) const CASES: [Case; 25] = [
    Case {
        id: "assets check",
        args: &[],
        verdict: Verdict::PreserveImplemented,
        reason: "canonical asset existence and section completeness are preserved",
    },
    Case {
        id: "assets outline",
        args: &[],
        verdict: Verdict::PreserveImplemented,
        reason: "legacy line-document statistics and section anchors are preserved",
    },
    Case {
        id: "assets query",
        args: &["service", "--top", "5"],
        verdict: Verdict::PreserveImplemented,
        reason: "legacy BM25 scoring, matched tokens, and result ordering are preserved",
    },
    Case {
        id: "assets read",
        args: &["coding", "--keys", "service"],
        verdict: Verdict::PreserveImplemented,
        reason: "legacy stage keys, section projection, and asset statistics are preserved",
    },
    Case {
        id: "assets section",
        args: &["A"],
        verdict: Verdict::PreserveImplemented,
        reason: "section lookup returns the same canonical Markdown",
    },
    Case {
        id: "assets stats",
        args: &[],
        verdict: Verdict::PreserveImplemented,
        reason: "legacy token, document, average-length, and section metrics are preserved",
    },
    Case {
        id: "automation status",
        args: &[],
        verdict: Verdict::PreserveImplemented,
        reason: "the complete automation configuration projection is preserved",
    },
    Case {
        id: "baseline diff",
        args: &["--report-file", "scan-report.json"],
        verdict: Verdict::PreserveImplemented,
        reason: "baseline delta classification and finding sets are preserved",
    },
    Case {
        id: "baseline inspect",
        args: &[],
        verdict: Verdict::PreserveImplemented,
        reason: "legacy sha256-prefixed integrity and baseline payload are preserved",
    },
    Case {
        id: "classify",
        args: &["--text", "large architecture migration"],
        verdict: Verdict::PreserveImplemented,
        reason: "routing action, spec derivation, and route rationale are preserved",
    },
    Case {
        id: "db audit",
        args: &[],
        verdict: Verdict::BreakingFixVerified,
        reason: "database paths are now confined to the registered workspace",
    },
    Case {
        id: "db explain",
        args: &["--profile", "local", "--sql", "SELECT id,name FROM item"],
        verdict: Verdict::BreakingFixVerified,
        reason: "read-only explain is preserved under workspace and SQL allowlists",
    },
    Case {
        id: "db profiles",
        args: &[],
        verdict: Verdict::BreakingFixVerified,
        reason: "profile listing is preserved while mutating --init is removed",
    },
    Case {
        id: "db query",
        args: &["--profile", "local", "--sql", "SELECT id,name FROM item"],
        verdict: Verdict::BreakingFixVerified,
        reason: "read-only rows are preserved while --write and outside-workspace DBs are removed",
    },
    Case {
        id: "evidence lookup",
        args: &[
            "--story",
            "STORY-EVIDENCE-001",
            "--command",
            "cargo test",
            "--input-fingerprint",
            "input-1",
            "--toolchain-fingerprint",
            "toolchain-1",
        ],
        verdict: Verdict::PreserveImplemented,
        reason: "reusable evidence identity, hash, artifact, and status are preserved",
    },
    Case {
        id: "git blame",
        args: &["--file", "tracked.txt"],
        verdict: Verdict::PreserveImplemented,
        reason: "structured blame entries are preserved",
    },
    Case {
        id: "git diff",
        args: &["--stat"],
        verdict: Verdict::PreserveImplemented,
        reason: "revision metadata and diff text are preserved",
    },
    Case {
        id: "git impact",
        args: &["--file", "tracked.txt", "--file", "src/lib.rs"],
        verdict: Verdict::PreserveImplemented,
        reason: "files, modules, extensions, and risk hints are preserved",
    },
    Case {
        id: "git log",
        args: &["--limit", "5"],
        verdict: Verdict::PreserveImplemented,
        reason: "structured commit metadata is preserved",
    },
    Case {
        id: "git status",
        args: &[],
        verdict: Verdict::PreserveImplemented,
        reason: "branch, dirty state, and porcelain entries are preserved",
    },
    Case {
        id: "perf doctor",
        args: &["--last", "10", "--limit", "5"],
        verdict: Verdict::PreserveImplemented,
        reason: "performance aggregates and diagnostic cardinality are preserved",
    },
    Case {
        id: "perf report",
        args: &["--last", "10", "--limit", "5"],
        verdict: Verdict::PreserveImplemented,
        reason: "all legacy performance summary buckets are preserved",
    },
    Case {
        id: "plugin list",
        args: &[],
        verdict: Verdict::BreakingFixVerified,
        reason: "project plugins are preserved; ambient global/master reads are intentionally removed",
    },
    Case {
        id: "plugin trace",
        args: &["fixture-skill"],
        verdict: Verdict::BreakingFixVerified,
        reason: "project resolution is preserved; ambient global/master targets are not trusted",
    },
    Case {
        id: "plugin validate",
        args: &[],
        verdict: Verdict::BreakingFixVerified,
        reason: "project validation is preserved within the registered workspace boundary",
    },
];
