use ae_sdd_contracts::session::SessionBootstrapRequest;
use ae_sdd_contracts::{AdapterId, ExternalSessionKey, SchemaVersion};
use ae_sdd_domain::{DelegationId, WorkspaceId};
use ae_sdd_session::{
    BootstrapPlan, BootstrapSnapshot, BootstrapStep, ExistingSessionInfo, SessionBootstrapError,
};

use super::*;

struct CapabilitySignInput<'a> {
    workspace_id: &'a str,
    session_id: &'a str,
    role: WireAgentRole,
    delegation_id: Option<&'a str>,
    grant: &'a ScopedGrantWire,
    engaged: bool,
    issued_at: u64,
    expires_at: u64,
}

impl RuntimeService {
    pub(super) fn session_open(&self, params: &RequestParams<Value>) -> RuntimeResult<Value> {
        let workspace_id = require(&params.workspace_id, "workspaceId")?.to_owned();
        let agent_id = require(&params.agent_id, "agentId")?.to_owned();
        let payload: SessionOpenPayload = decode_value(params.payload.clone())?;
        if payload.context.is_some() {
            return Err(RuntimeError::new(
                StableErrorCode::RoleOperationForbidden,
                "caller-supplied session context is not authoritative",
            ));
        }
        let external_key_hash = hex::encode(Sha256::digest(payload.external_key.as_bytes()));
        let key = require_idempotency(params)?;
        let scope = format!(
            "session-open\0{}\0{workspace_id}\0{external_key_hash}",
            self.boot_id
        );
        let digest = canonical_digest(&json!({
            "bootId":self.boot_id.to_string(),
            "workspaceId":workspace_id,
            "agentId":agent_id,
            "workItemId":params.work_item_id,
            "externalKeyHash":external_key_hash,
            "payload":payload,
        }))?;
        let now = self.clock.now_unix_ms();
        let expires = now.saturating_add(self.config.session_ttl_ms);

        let (result, previous_record, bootstrap_plan) = {
            let mut state = self.lock_state()?;
            let mode = state
                .workspaces
                .get(&workspace_id)
                .ok_or_else(|| project_mismatch("workspace is not registered"))?
                .result
                .mode;
            let engaged = matches!(
                mode,
                WorkspaceMode::RustCanary | WorkspaceMode::RustSoleWriter
            );
            if payload.engaged != engaged {
                return Err(RuntimeError::new(
                    StableErrorCode::RoleOperationForbidden,
                    "caller engaged mode differs from the daemon workspace policy",
                ));
            }

            let existing = state
                .sessions
                .values()
                .find(|session| {
                    session.external_key_hash == external_key_hash
                        && session.workspace_id != workspace_id
                })
                .cloned()
                .or_else(|| {
                    state
                        .session_by_external
                        .get(&(workspace_id.clone(), external_key_hash.clone()))
                        .and_then(|session_id| state.sessions.get(session_id))
                        .cloned()
                })
                .or_else(|| {
                    state
                        .sessions
                        .values()
                        .find(|session| session.external_key_hash == external_key_hash)
                        .cloned()
                });
            let session_id = match existing.as_ref() {
                Some(previous) => previous.result.session_id.clone(),
                None => match payload.role {
                    WireAgentRole::Root => {
                        if params.session_id.is_some() {
                            return Err(RuntimeError::new(
                                StableErrorCode::RoleOperationForbidden,
                                "root session identity is generated by the daemon",
                            ));
                        }
                        Uuid::new_v4().to_string()
                    }
                    _ => params.session_id.clone().ok_or_else(|| {
                        RuntimeError::new(
                            StableErrorCode::DelegationAttestationFailed,
                            "child session requires its attested sessionId",
                        )
                    })?,
                },
            };
            SessionId::from_str(&session_id)
                .map_err(|_| schema_error("sessionId is not a UUID"))?;

            let authoritative_grant = match existing.as_ref() {
                Some(previous) if previous.workspace_id == workspace_id => self
                    .validate_delegated_open(
                        previous.result.role,
                        previous.delegation_id.as_deref(),
                        &session_id,
                    )?,
                Some(previous) => previous.grant.normalized()?,
                None => self.validate_delegated_open(
                    payload.role,
                    payload.delegation_id.as_deref(),
                    &session_id,
                )?,
            };
            let bootstrap_plan = self.plan_session_bootstrap(
                &workspace_id,
                &payload,
                existing.as_ref(),
                &authoritative_grant,
                engaged,
                params.work_item_id.is_none(),
            )?;
            if bootstrap_plan.steps().contains(&BootstrapStep::OpenSession) != existing.is_none() {
                return Err(RuntimeError::new(
                    StableErrorCode::ExternalStateConflict,
                    "session bootstrap plan conflicts with the authoritative session snapshot",
                ));
            }

            if let Some(previous) = existing {
                if previous.result.role != WireAgentRole::Root
                    && previous.grant.normalized()? != authoritative_grant
                {
                    return Err(RuntimeError::new(
                        StableErrorCode::DelegationAttestationFailed,
                        "durable child session grant differs from its delegation",
                    ));
                }
                let session = state.sessions.get_mut(&session_id).ok_or_else(|| {
                    RuntimeError::new(
                        StableErrorCode::ExternalStateConflict,
                        "external session snapshot changed during bootstrap",
                    )
                })?;
                let recovered_root_label_drift = !session.active
                    && session.result.role == WireAgentRole::Root
                    && payload.role == WireAgentRole::Root;
                if session.result.role != payload.role
                    || (session.agent_id != agent_id && !recovered_root_label_drift)
                {
                    return Err(turn_mismatch(
                        "external session identity is bound to another agent or role",
                    ));
                }
                if recovered_root_label_drift {
                    session.agent_id.clone_from(&agent_id);
                }
                session.active = true;
                session.grant = authoritative_grant;
                session.result.engaged = engaged;
                if params.work_item_id.is_some() {
                    session.current_work_item = params.work_item_id.clone();
                }
                session.result.expires_at_unix_ms = expires;
                session.result.capability_token = self.sign_capability(CapabilitySignInput {
                    workspace_id: &workspace_id,
                    session_id: &session_id,
                    role: session.result.role,
                    delegation_id: session.delegation_id.as_deref(),
                    grant: &session.grant,
                    engaged,
                    issued_at: now,
                    expires_at: expires,
                })?;
                (session.result.clone(), Some(previous), bootstrap_plan)
            } else {
                if state.sessions.values().filter(|item| item.active).count()
                    >= self.config.max_sessions
                {
                    return Err(RuntimeError::new(
                        StableErrorCode::SubscriberBackpressure,
                        "active session capacity is exhausted",
                    ));
                }
                if state.sessions.contains_key(&session_id) {
                    return Err(RuntimeError::new(
                        StableErrorCode::TurnIdentityMismatch,
                        "sessionId is already bound to another physical session",
                    ));
                }
                let token = self.sign_capability(CapabilitySignInput {
                    workspace_id: &workspace_id,
                    session_id: &session_id,
                    role: payload.role,
                    delegation_id: payload.delegation_id.as_deref(),
                    grant: &authoritative_grant,
                    engaged,
                    issued_at: now,
                    expires_at: expires,
                })?;
                let result = SessionResult {
                    session_id: session_id.clone(),
                    role: payload.role,
                    engaged,
                    expires_at_unix_ms: expires,
                    context_generation: 0,
                    capability_token: token,
                };
                let record = SessionRecord {
                    workspace_id: workspace_id.clone(),
                    agent_id,
                    external_key_hash: external_key_hash.clone(),
                    current_work_item: params.work_item_id.clone(),
                    result: result.clone(),
                    delegation_id: payload.delegation_id,
                    grant: authoritative_grant,
                    current_turn_id: None,
                    current_turn_seq: 0,
                    active: true,
                };
                state.session_by_external.insert(
                    (workspace_id.clone(), external_key_hash.clone()),
                    session_id.clone(),
                );
                state.sessions.insert(session_id, record);
                (result, None, bootstrap_plan)
            }
        };
        let mut value = to_value(&result)?;
        let object = value.as_object_mut().ok_or_else(|| {
            RuntimeError::new(
                StableErrorCode::ExternalStateConflict,
                "session result is not a canonical object",
            )
        })?;
        object.insert(
            "bootstrapPlanDigest".to_owned(),
            Value::String(hex::encode(bootstrap_plan.plan_digest())),
        );
        if bootstrap_plan
            .steps()
            .contains(&BootstrapStep::ProjectContext)
            && let Some(work_item_id) = params.work_item_id.as_deref()
            && let Err(error) =
                self.project_session_context(&workspace_id, &result.session_id, work_item_id)
        {
            self.rollback_open(
                &workspace_id,
                &external_key_hash,
                &result.session_id,
                previous_record.as_ref(),
            )?;
            return Err(error);
        }
        let committed = match self.commit_session_identity(
            "session.open",
            &scope,
            key,
            &digest,
            &result.session_id,
            &value,
        ) {
            Ok(snapshot) => snapshot,
            Err(error) => {
                self.rollback_open(
                    &workspace_id,
                    &external_key_hash,
                    &result.session_id,
                    previous_record.as_ref(),
                )?;
                return Err(error);
            }
        };
        let response = if committed.replayed {
            self.restore_replayed_session(&committed)?
        } else {
            value
        };
        if !committed.replayed {
            self.append_runtime_event(
                "session.opened",
                json!({"sessionId":result.session_id}),
                Some(workspace_id),
                Some(result.session_id),
                None,
            )?;
        }
        Ok(response)
    }

    /// Installs the context projection a session holds for its bound Work Item.
    ///
    /// Shared by the `ProjectContext` bootstrap step in `session.open` and the
    /// bind-after-create path, so a session that names its Work Item at open
    /// and a session that creates it mid-flight hold the exact same
    /// projection.
    pub(super) fn project_session_context(
        &self,
        workspace_id: &str,
        session_id: &str,
        work_item_id: &str,
    ) -> RuntimeResult<()> {
        let (workspace, role) = {
            let state = self.lock_state()?;
            let record = state
                .workspaces
                .get(workspace_id)
                .ok_or_else(|| project_mismatch("workspace is not registered"))?;
            let session = state.sessions.get(session_id).ok_or_else(session_expired)?;
            (
                BusinessWorkspace {
                    workspace_id: record.result.workspace_id.clone(),
                    canonical_root: record.result.canonical_root.clone(),
                    project_key: record.result.project_key.clone(),
                    mode: record.result.mode,
                    agent_role: Some(AgentRole::from(session.result.role)),
                    agent_grant: Some(session.grant.to_domain()?),
                    caller_kind: None,
                    inventory_generation: record.result.inventory_generation,
                },
                session.result.role,
            )
        };
        let projection = self.business.project_context(
            &workspace,
            work_item_id,
            session_id,
            AgentRole::from(role),
        )?;
        self.context.put(projection).map(|_| ())
    }

    /// Binds the calling session to the Work Item a successful
    /// `workitem.create` just created.
    ///
    /// `workitem.create` is Workspace-scoped: the Work Item is its output, so
    /// the request cannot name it and the business authority mints the
    /// business key. Without this binding the session that ran the bootstrap
    /// create would stay unbound and every later Hook would be unattributed —
    /// the first-turn deadlock. The binding persists through the same durable
    /// session-identity path `session.open` uses and installs the same
    /// context projection, so creating a Work Item and opening a session on
    /// one become interchangeable.
    ///
    /// Binding never fails the underlying operation: the create already
    /// committed in the business authority, so reporting a failure here would
    /// tell the caller a created Work Item does not exist and invite a
    /// duplicate retry. The in-memory binding stands on a degraded commit and
    /// the next session identity write (heartbeat, reopen) repairs the
    /// durable record. A caller without a session (admin/CLI) has nothing to
    /// bind and is skipped.
    pub(super) fn bind_created_work_item(
        &self,
        params: &RequestParams<Value>,
        value: &Value,
    ) -> RuntimeResult<()> {
        let Some((session_id, work_item_id)) = created_work_item_binding(params, value) else {
            return Ok(());
        };
        let workspace_id = {
            let mut state = self.lock_state()?;
            let Some(session) = state.sessions.get_mut(&session_id) else {
                return Ok(());
            };
            session.current_work_item = Some(work_item_id.clone());
            session.workspace_id.clone()
        };
        let committed = self
            .persist_session(&session_id)
            .and_then(|()| self.project_session_context(&workspace_id, &session_id, &work_item_id));
        if let Err(error) = committed {
            drop(self.append_runtime_event(
                "session.work-item.bind-degraded",
                json!({
                    "errorCode":format!("{:?}", error.code()),
                    "message":error.message(),
                }),
                Some(workspace_id),
                Some(session_id),
                Some(work_item_id),
            ));
        }
        Ok(())
    }

    fn plan_session_bootstrap(
        &self,
        workspace_id: &str,
        payload: &SessionOpenPayload,
        existing: Option<&SessionRecord>,
        grant: &ScopedGrantWire,
        engaged: bool,
        context_ready: bool,
    ) -> RuntimeResult<BootstrapPlan> {
        let workspace_id = WorkspaceId::from_str(workspace_id)
            .map_err(|_| schema_error("workspaceId is not a UUID"))?;
        let external_session_key = ExternalSessionKey::new(payload.external_key.clone())
            .map_err(|_| schema_error("externalKey is not a portable session identity"))?;
        let adapter_id = AdapterId::new("runtime.session-open")
            .expect("static runtime session adapter ID is valid");
        let (role, delegation_id) = existing.map_or(
            (payload.role, payload.delegation_id.as_deref()),
            |previous| (previous.result.role, previous.delegation_id.as_deref()),
        );
        let delegation_id = delegation_id
            .map(DelegationId::from_str)
            .transpose()
            .map_err(|_| schema_error("delegationId is not a UUID"))?;
        let capabilities = grant
            .capabilities
            .iter()
            .map(|capability| {
                CapabilityId::new(capability.clone()).map_err(|_| {
                    RuntimeError::new(
                        StableErrorCode::ExternalStateConflict,
                        "authoritative session grant contains an invalid capability",
                    )
                })
            })
            .collect::<RuntimeResult<Vec<_>>>()?;
        let request = SessionBootstrapRequest::new(
            SchemaVersion::V1,
            workspace_id,
            external_session_key,
            adapter_id,
            AgentRole::from(role),
            engaged,
            delegation_id,
            capabilities,
            None,
        )
        .map_err(|_| schema_error("session bootstrap request violates its frozen contract"))?;
        let existing_session = existing
            .map(|previous| {
                let session_id = SessionId::from_str(&previous.result.session_id)
                    .map_err(|_| schema_error("durable sessionId is not a UUID"))?;
                let workspace_id = WorkspaceId::from_str(&previous.workspace_id)
                    .map_err(|_| schema_error("durable workspaceId is not a UUID"))?;
                Ok(ExistingSessionInfo::new(session_id, workspace_id))
            })
            .transpose()?;
        let snapshot = BootstrapSnapshot::new(true, existing_session, context_ready);

        self.session_bootstrap()
            .bootstrap(&request, &snapshot)
            .map_err(|error| match error {
                SessionBootstrapError::CrossWorkspaceSession => {
                    project_mismatch("external session is already bound to a different workspace")
                }
            })
    }

    fn rollback_open(
        &self,
        workspace_id: &str,
        external_key: &str,
        session_id: &str,
        previous: Option<&SessionRecord>,
    ) -> RuntimeResult<()> {
        let mut state = self.lock_state()?;
        if let Some(previous) = previous {
            state
                .sessions
                .insert(session_id.to_owned(), previous.clone());
        } else {
            state.sessions.remove(session_id);
            state
                .session_by_external
                .remove(&(workspace_id.to_owned(), external_key.to_owned()));
        }
        Ok(())
    }

    pub(super) fn session_heartbeat(&self, params: &RequestParams<Value>) -> RuntimeResult<Value> {
        let identity = self.session_identity(params, false)?;
        let key = require_idempotency(params)?;
        let digest = canonical_digest(&json!({
            "workspaceId":identity.workspace_id,
            "sessionId":identity.session_id,
            "payload":params.payload,
        }))?;
        let scope = format!("session-heartbeat\0{}", identity.session_id);
        let now = self.clock.now_unix_ms();
        let expires = now.saturating_add(self.config.session_ttl_ms);
        let (value, previous) = {
            let mut state = self.lock_state()?;
            let session = state
                .sessions
                .get_mut(&identity.session_id)
                .ok_or_else(session_expired)?;
            let previous = session.clone();
            session.result.expires_at_unix_ms = expires;
            session.result.capability_token = self.sign_capability(CapabilitySignInput {
                workspace_id: &identity.workspace_id,
                session_id: &identity.session_id,
                role: session.result.role,
                delegation_id: session.delegation_id.as_deref(),
                grant: &session.grant,
                engaged: session.result.engaged,
                issued_at: now,
                expires_at: expires,
            })?;
            (to_value(&session.result)?, previous)
        };
        let committed = match self.commit_session_identity(
            "session.heartbeat",
            &scope,
            key,
            &digest,
            &identity.session_id,
            &value,
        ) {
            Ok(snapshot) => snapshot,
            Err(error) => {
                self.lock_state()?
                    .sessions
                    .insert(identity.session_id.clone(), previous);
                return Err(error);
            }
        };
        let response = if committed.replayed {
            self.restore_replayed_session(&committed)?
        } else {
            value
        };
        if !committed.replayed {
            self.append_runtime_event(
                "session.heartbeat",
                json!({"sessionId":identity.session_id}),
                Some(identity.workspace_id),
                Some(identity.session_id),
                None,
            )?;
        }
        Ok(response)
    }

    pub(super) fn session_close(&self, params: &RequestParams<Value>) -> RuntimeResult<Value> {
        let identity = self.session_identity(params, false)?;
        let key = require_idempotency(params)?;
        let digest = canonical_digest(&json!({
            "workspaceId":identity.workspace_id,
            "sessionId":identity.session_id,
            "payload":params.payload,
        }))?;
        let scope = format!("session-close\0{}", identity.session_id);
        let (value, previous) = {
            let mut state = self.lock_state()?;
            let session = state
                .sessions
                .get_mut(&identity.session_id)
                .ok_or_else(session_expired)?;
            let previous = session.clone();
            session.active = false;
            (to_value(&session.result)?, previous)
        };
        let committed = match self.commit_session_identity(
            "session.close",
            &scope,
            key,
            &digest,
            &identity.session_id,
            &value,
        ) {
            Ok(snapshot) => snapshot,
            Err(error) => {
                self.lock_state()?
                    .sessions
                    .insert(identity.session_id.clone(), previous);
                return Err(error);
            }
        };
        if !committed.replayed {
            self.append_runtime_event(
                "session.closed",
                json!({"sessionId":identity.session_id}),
                Some(identity.workspace_id),
                Some(identity.session_id),
                None,
            )?;
        }
        Ok(value)
    }

    fn commit_session_identity(
        &self,
        operation: &str,
        scope: &str,
        key: &str,
        request_digest: &str,
        session_id: &str,
        response: &Value,
    ) -> RuntimeResult<RuntimeIdentitySnapshot> {
        let (session, workspace) = {
            let state = self.lock_state()?;
            let session = state
                .sessions
                .get(session_id)
                .cloned()
                .ok_or_else(session_expired)?;
            let workspace = state
                .workspaces
                .get(&session.workspace_id)
                .cloned()
                .ok_or_else(|| project_mismatch("session workspace is not registered"))?;
            (session, workspace)
        };
        let previous_session = self
            .persistence
            .list_identity_snapshots(RuntimeIdentityKind::Session)?
            .into_iter()
            .filter_map(|snapshot| snapshot.session)
            .find(|record| record.session_id == session_id);
        let previous_workspace = self
            .persistence
            .list_identity_snapshots(RuntimeIdentityKind::Workspace)?
            .into_iter()
            .map(|snapshot| snapshot.workspace)
            .find(|record| record.workspace_id == session.workspace_id);
        let (root_session_id, parent_session_id) = match session.result.role {
            WireAgentRole::Root => (session_id.to_owned(), None),
            _ => {
                let delegation_id = session.delegation_id.as_deref().ok_or_else(|| {
                    RuntimeError::new(
                        StableErrorCode::DelegationAttestationFailed,
                        "child session lacks its delegation lineage",
                    )
                })?;
                let (root, parent) = self.delegation.session_lineage(delegation_id)?;
                (root, Some(parent))
            }
        };
        let now = self.clock.now_unix_ms();
        let mut secret_free_response = response.clone();
        secret_free_response
            .as_object_mut()
            .ok_or_else(|| schema_error("session response must be an object"))?
            .remove("capabilityToken");
        self.persistence
            .commit_identity_bundle(RuntimeIdentityTransition {
                operation: operation.to_owned(),
                scope_digest: canonical_digest(&json!({
                    "domain":"runtime-session-identity/v1",
                    "scope":scope,
                }))?,
                idempotency_key: key.to_owned(),
                request_digest: request_digest.to_owned(),
                expected_workspace_mode: Some(workspace.result.mode),
                expected_inventory_generation: Some(workspace.result.inventory_generation),
                expected_session_status: previous_session
                    .as_ref()
                    .map(|record| record.status.clone()),
                expected_delegation_status: None,
                expected_context_generation: previous_session
                    .as_ref()
                    .map(|record| record.context_generation),
                snapshot: RuntimeIdentitySnapshot {
                    identity_kind: RuntimeIdentityKind::Session,
                    workspace: RuntimeWorkspaceRecord {
                        workspace_id: workspace.result.workspace_id.clone(),
                        canonical_root: workspace.result.canonical_root,
                        project_key: workspace.result.project_key,
                        mode: workspace.result.mode,
                        inventory_generation: workspace.result.inventory_generation,
                        dirty: false,
                        created_at_unix_ms: previous_workspace
                            .as_ref()
                            .map_or(now, |record| record.created_at_unix_ms),
                        updated_at_unix_ms: now,
                    },
                    session: Some(RuntimeSessionRecord {
                        session_id: session.result.session_id,
                        agent_id: session.agent_id,
                        workspace_id: session.workspace_id,
                        external_key_hash: session.external_key_hash,
                        role: session.result.role,
                        root_session_id,
                        parent_session_id,
                        delegation_id: session.delegation_id,
                        engaged: session.result.engaged,
                        current_work_item: session.current_work_item,
                        grant: session.grant,
                        context_generation: session.result.context_generation,
                        expires_at_unix_ms: session.result.expires_at_unix_ms,
                        status: if session.active {
                            "active".to_owned()
                        } else {
                            "closed".to_owned()
                        },
                        created_at_unix_ms: previous_session
                            .as_ref()
                            .map_or(now, |record| record.created_at_unix_ms),
                        updated_at_unix_ms: now,
                    }),
                    delegation: None,
                    host_action: None,
                    attestation: None,
                    response: secret_free_response,
                    replayed: false,
                },
                committed_at_unix_ms: now,
            })
    }

    /// Replays a stored session-identity receipt without restoring its
    /// after-image.
    ///
    /// The receipt is historical: the session may have bound a Work Item,
    /// refreshed its grant, or completed a compact since the receipt
    /// committed. Writing the after-image back would roll those mutations off
    /// the in-memory session — a replayed `session.open` would silently unbind
    /// the Work Item a later `workitem.create` installed. The replay therefore
    /// only re-checks the immutable identity and re-signs the capability from
    /// the live record, so the returned proof matches the session's current
    /// grant, engagement and expiry; the stored response body is returned
    /// as-is apart from that fresh token.
    fn restore_replayed_session(&self, snapshot: &RuntimeIdentitySnapshot) -> RuntimeResult<Value> {
        let durable = snapshot.session.as_ref().ok_or_else(|| {
            RuntimeError::new(
                StableErrorCode::ExternalStateConflict,
                "replayed session identity receipt lacks a session after-image",
            )
        })?;
        let capability_token = {
            let mut state = self.lock_state()?;
            let session = state
                .sessions
                .get_mut(&durable.session_id)
                .ok_or_else(session_expired)?;
            if session.workspace_id != durable.workspace_id
                || session.agent_id != durable.agent_id
                || session.external_key_hash != durable.external_key_hash
                || session.result.role != durable.role
                || session.delegation_id != durable.delegation_id
            {
                return Err(RuntimeError::new(
                    StableErrorCode::ExternalStateConflict,
                    "replayed session identity differs from the in-memory session",
                ));
            }
            let capability_token = self.sign_capability(CapabilitySignInput {
                workspace_id: &session.workspace_id,
                session_id: &session.result.session_id,
                role: session.result.role,
                delegation_id: session.delegation_id.as_deref(),
                grant: &session.grant,
                engaged: session.result.engaged,
                issued_at: self.clock.now_unix_ms(),
                expires_at: session.result.expires_at_unix_ms,
            })?;
            session
                .result
                .capability_token
                .clone_from(&capability_token);
            capability_token
        };
        let mut response = snapshot.response.clone();
        response
            .as_object_mut()
            .ok_or_else(|| {
                RuntimeError::new(
                    StableErrorCode::ExternalStateConflict,
                    "replayed session response is not an object",
                )
            })?
            .insert(
                "capabilityToken".to_owned(),
                Value::String(capability_token),
            );
        Ok(response)
    }

    pub(super) fn persist_session(&self, session_id: &str) -> RuntimeResult<()> {
        let (generation, active) = {
            let state = self.lock_state()?;
            let session = state.sessions.get(session_id).ok_or_else(session_expired)?;
            (session.result.context_generation, session.active)
        };
        let now = self.clock.now_unix_ms();
        let response = json!({
            "sessionId":session_id,
            "contextGeneration":generation,
            "status":if active { "active" } else { "closed" },
        });
        let scope = format!("session-internal\0{session_id}");
        let key = format!("{generation}-{}-{now}", u8::from(active));
        let digest = canonical_digest(&response)?;
        self.commit_session_identity(
            "session.internal.update",
            &scope,
            &key,
            &digest,
            session_id,
            &response,
        )?;
        Ok(())
    }

    pub(super) fn validate_delegated_open(
        &self,
        role: WireAgentRole,
        delegation_id: Option<&str>,
        session_id: &str,
    ) -> RuntimeResult<ScopedGrantWire> {
        match role {
            WireAgentRole::Root if delegation_id.is_none() => Ok(crate::grant::root_grant()),
            WireAgentRole::Root => Err(RuntimeError::new(
                StableErrorCode::DelegationAttestationFailed,
                "root session cannot carry a delegation",
            )),
            _ => {
                let delegation_id = delegation_id.ok_or_else(|| {
                    RuntimeError::new(
                        StableErrorCode::DelegationAttestationFailed,
                        "child session requires a physical delegation",
                    )
                })?;
                let projection = self.delegation.status(session_id, delegation_id)?;
                if projection.status != "running"
                    || projection.child_session_id.as_deref() != Some(session_id)
                    || projection.child_role != role
                {
                    return Err(RuntimeError::new(
                        StableErrorCode::DelegationAttestationFailed,
                        "child session does not match the attested delegation",
                    ));
                }
                let attestation = self
                    .persistence
                    .list_identity_snapshots(RuntimeIdentityKind::Delegation)?
                    .into_iter()
                    .find_map(|snapshot| {
                        snapshot.attestation.filter(|attestation| {
                            attestation.delegation_id == delegation_id
                                && attestation.physical_session_id == session_id
                        })
                    })
                    .ok_or_else(|| {
                        RuntimeError::new(
                            StableErrorCode::DelegationAttestationFailed,
                            "child session lacks its typed physical attestation",
                        )
                    })?;
                if attestation.accepted_boot_id != self.boot_id.to_string()
                    || self
                        .delegation
                        .deadline_unix_ms(session_id, delegation_id)?
                        <= self.clock.now_unix_ms()
                    || attestation.grant.normalized()? != projection.grant.normalized()?
                {
                    return Err(RuntimeError::new(
                        StableErrorCode::DelegationAttestationFailed,
                        "child session grant or boot differs from its physical attestation",
                    ));
                }
                let grant = attestation.grant.normalized()?;
                crate::grant::validate_session_grant(role, &grant)?;
                Ok(grant)
            }
        }
    }

    fn sign_capability(&self, input: CapabilitySignInput<'_>) -> RuntimeResult<String> {
        let capability_id = if input.engaged {
            "hook.engaged"
        } else {
            "hook.unengaged"
        };
        let claims = CapabilityClaims::new(
            self.capability_signer.key_id(),
            self.boot_id,
            CapabilityId::new(capability_id).expect("static capability ID is valid"),
            SessionId::from_str(input.session_id)
                .map_err(|_| schema_error("invalid session ID"))?,
            input.role.into(),
            input
                .delegation_id
                .map(DelegationId::from_str)
                .transpose()
                .map_err(|_| schema_error("invalid delegation ID"))?,
            capability_grant_digest(
                input.workspace_id,
                input.session_id,
                input.role,
                input.delegation_id,
                input.grant,
                &self.config.policy_digest,
                capability_id,
            )?,
            input.issued_at,
            input.expires_at,
        )
        .map_err(|_| schema_error("session capability claims are invalid"))?;
        self.capability_signer
            .sign(claims)
            .and_then(|token| token.encode())
            .map_err(|_| {
                RuntimeError::new(
                    StableErrorCode::ExternalStateConflict,
                    "session capability could not be signed",
                )
            })
    }

    pub(super) fn session_identity(
        &self,
        params: &RequestParams<Value>,
        require_turn: bool,
    ) -> RuntimeResult<TrustedSession> {
        let workspace_id = require(&params.workspace_id, "workspaceId")?;
        let session_id = require(&params.session_id, "sessionId")?;
        let agent_id = require(&params.agent_id, "agentId")?;
        if require_turn && params.turn_id.is_none() {
            return Err(schema_error("turnId is required for engaged Hook requests"));
        }
        let state = self.lock_state()?;

        let session = state.sessions.get(session_id).ok_or_else(session_expired)?;
        if !session.active || self.clock.now_unix_ms() >= session.result.expires_at_unix_ms {
            return Err(session_expired());
        }
        if session.workspace_id != workspace_id || session.agent_id != agent_id {
            return Err(turn_mismatch(
                "session does not belong to the supplied workspace/agent identity",
            ));
        }
        let encoded = params.capability_token.as_deref().ok_or_else(|| {
            RuntimeError::new(
                StableErrorCode::SessionExpired,
                "boot-scoped session capability proof is required",
            )
        })?;
        let token = CapabilityToken::decode(encoded).map_err(|_| {
            RuntimeError::new(
                StableErrorCode::SessionExpired,
                "session capability proof is malformed",
            )
        })?;
        let claims = self
            .capability_signer
            .public_key()
            .verify(&token, self.clock.now_unix_ms())
            .map_err(|_| {
                RuntimeError::new(
                    StableErrorCode::SessionExpired,
                    "session capability proof is forged, stale, or expired",
                )
            })?;
        let grant = crate::grant::validate_session_grant(session.result.role, &session.grant)?;
        let expected_grant_digest = capability_grant_digest(
            workspace_id,
            session_id,
            session.result.role,
            session.delegation_id.as_deref(),
            &session.grant,
            &self.config.policy_digest,
            claims.capability_id().as_str(),
        )?;
        if claims.session_id().to_string() != session_id
            || AgentRole::from(session.result.role) != claims.role()
            || claims.delegation_id().map(|value| value.to_string()) != session.delegation_id
            || claims.capability_id().as_str()
                != if session.result.engaged {
                    "hook.engaged"
                } else {
                    "hook.unengaged"
                }
            || claims.grant_digest() != expected_grant_digest
        {
            return Err(RuntimeError::new(
                StableErrorCode::TurnIdentityMismatch,
                "session capability proof does not bind this session role/delegation",
            ));
        }
        Ok(TrustedSession {
            workspace_id: workspace_id.to_owned(),
            session_id: session_id.to_owned(),
            role: session.result.role,
            grant,
            engaged: session.result.engaged,
            capability_id: claims.capability_id().as_str().to_owned(),
        })
    }

    pub(super) fn validate_turn(
        &self,
        session_id: &str,
        turn_id: &str,
        turn_seq: u64,
    ) -> RuntimeResult<()> {
        if turn_seq == 0 {
            return Err(turn_mismatch("turn sequence must be greater than zero"));
        }
        let mut state = self.lock_state()?;
        let session = state
            .sessions
            .get_mut(session_id)
            .ok_or_else(session_expired)?;
        match session.current_turn_id.as_deref() {
            None if turn_seq == 1 => {
                session.current_turn_id = Some(turn_id.to_owned());
                session.current_turn_seq = 1;
                Ok(())
            }
            Some(current) if current == turn_id && turn_seq == session.current_turn_seq => Ok(()),
            Some(_) if turn_seq == session.current_turn_seq.saturating_add(1) => {
                session.current_turn_id = Some(turn_id.to_owned());
                session.current_turn_seq = turn_seq;
                Ok(())
            }
            _ => Err(turn_mismatch(
                "turn identity or sequence does not match the trusted session",
            )),
        }
    }

    /// Allocates the turn for one Hook event when the host cannot name it.
    ///
    /// A Hook runs as a short-lived host subprocess with no durable state, so
    /// it cannot know the monotonic turn sequence its own session is on. The
    /// daemon owns that sequence, so it allocates here instead of rejecting the
    /// event. `hook.user_prompt` is the turn boundary and opens a new turn;
    /// the other three run inside a turn already in flight and join it. A Hook
    /// that arrives before any prompt still gets turn 1 rather than a failure,
    /// because a host may not implement `UserPromptSubmit` at all.
    pub(super) fn allocate_turn(
        &self,
        session_id: &str,
        method: RpcMethod,
    ) -> RuntimeResult<(String, u64)> {
        let mut state = self.lock_state()?;
        let session = state
            .sessions
            .get_mut(session_id)
            .ok_or_else(session_expired)?;
        let opens_turn = method == RpcMethod::HookUserPrompt || session.current_turn_id.is_none();
        if !opens_turn {
            let turn_id = session
                .current_turn_id
                .clone()
                .ok_or_else(|| turn_mismatch("session has no turn in flight"))?;
            return Ok((turn_id, session.current_turn_seq));
        }
        let turn_id = Uuid::new_v4().to_string();
        let turn_seq = session.current_turn_seq.saturating_add(1);
        session.current_turn_id = Some(turn_id.clone());
        session.current_turn_seq = turn_seq;
        Ok((turn_id, turn_seq))
    }

    /// Resolves the Work Item a Hook event is attributed to.
    ///
    /// Hooks are Session-scoped, so the Work Item is attribution rather than
    /// authority and stays absent until routing binds one. A caller may not
    /// claim a Work Item that contradicts the session binding; omitting the
    /// field always adopts the binding.
    pub(super) fn resolve_hook_work_item(
        &self,
        session_id: &str,
        requested: Option<&str>,
    ) -> RuntimeResult<Option<String>> {
        let state = self.lock_state()?;
        let session = state.sessions.get(session_id).ok_or_else(session_expired)?;
        let bound = session.current_work_item.clone();
        match (requested.filter(|value| !value.trim().is_empty()), &bound) {
            (Some(requested), Some(bound)) if requested != bound.as_str() => Err(turn_mismatch(
                "Hook Work Item differs from the session binding",
            )),
            (Some(requested), _) => Ok(Some(requested.to_owned())),
            (None, _) => Ok(bound),
        }
    }
}

/// Resolves the session-to-Work-Item binding a successful operation result
/// implies, when it implies one.
///
/// Only `workitem.create` binds: every other Work Item operation already ran
/// under the Work Item it names. The business authority's returned
/// `data.workItemId` wins — it echoes an explicitly named item and is the
/// only source for a daemon-minted one; the request field is the fallback for
/// an adapter that omits the echo.
fn created_work_item_binding(
    params: &RequestParams<Value>,
    value: &Value,
) -> Option<(String, String)> {
    let is_create = params
        .payload
        .get("operation")
        .and_then(Value::as_str)
        .and_then(|name| ae_sdd_operations::OperationName::from_str(name).ok())
        == Some(ae_sdd_operations::OperationName::WorkItemCreate);
    if !is_create {
        return None;
    }
    let session_id = params.session_id.clone()?;
    let work_item_id = value
        .get("data")
        .and_then(|data| data.get("workItemId"))
        .and_then(Value::as_str)
        .or(params.work_item_id.as_deref())?;
    Some((session_id, work_item_id.to_owned()))
}

fn capability_grant_digest(
    workspace_id: &str,
    session_id: &str,
    role: WireAgentRole,
    delegation_id: Option<&str>,
    grant: &ScopedGrantWire,
    policy_digest: &str,
    capability_id: &str,
) -> RuntimeResult<GrantDigest> {
    let role = match role {
        WireAgentRole::Root => "root",
        WireAgentRole::Series => "series",
        WireAgentRole::Task => "task",
        WireAgentRole::Reviewer => "reviewer",
    };
    let mut material = format!(
        "{workspace_id}\0{session_id}\0{role}\0{}\0{policy_digest}\0{capability_id}",
        delegation_id.unwrap_or("")
    )
    .into_bytes();
    material.push(0);
    let normalized = grant.normalized()?;
    material.extend(serde_json::to_vec(&normalized).map_err(canonical_error)?);
    Ok(GrantDigest::digest(material))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::GrantPathWire;

    fn operation_params(
        operation: &str,
        session_id: Option<&str>,
        work_item_id: Option<&str>,
    ) -> RequestParams<Value> {
        RequestParams {
            protocol_version: PROTOCOL_VERSION_V1.to_owned(),
            workspace_id: None,
            agent_id: None,
            session_id: session_id.map(str::to_owned),
            capability_token: None,
            turn_id: None,
            work_item_id: work_item_id.map(str::to_owned),
            lease_id: None,
            fencing_token: None,
            expected_revision: None,
            idempotency_key: None,
            confirmation: None,
            deadline_ms: 1_000,
            payload: json!({"operation":operation,"payload":{}}),
        }
    }

    #[test]
    fn only_a_workitem_create_result_implies_a_session_binding() {
        let params = operation_params("state.transition", Some("session"), Some("WORK"));
        let value = json!({"data":{"workItemId":"WORK"}});
        assert_eq!(created_work_item_binding(&params, &value), None);
    }

    #[test]
    fn a_create_without_a_session_binds_nothing() {
        // An admin/CLI caller has no session to bind; the create still
        // succeeds and the binding step skips it silently.
        let params = operation_params("workitem.create", None, None);
        let value = json!({"data":{"workItemId":"WORK-MINTED"}});
        assert_eq!(created_work_item_binding(&params, &value), None);
    }

    #[test]
    fn the_returned_business_key_wins_over_the_request_field() {
        let params = operation_params("workitem.create", Some("session"), Some("WORK-NAMED"));
        let value = json!({"data":{"workItemId":"WORK-ECHOED"}});
        assert_eq!(
            created_work_item_binding(&params, &value),
            Some(("session".to_owned(), "WORK-ECHOED".to_owned()))
        );
    }

    #[test]
    fn the_request_field_is_the_fallback_when_the_result_omits_the_key() {
        let params = operation_params("workitem.create", Some("session"), Some("WORK-NAMED"));
        assert_eq!(
            created_work_item_binding(&params, &json!({"ok":true})),
            Some(("session".to_owned(), "WORK-NAMED".to_owned()))
        );
        let unnamed = operation_params("workitem.create", Some("session"), None);
        assert_eq!(
            created_work_item_binding(&unnamed, &json!({"ok":true})),
            None
        );
    }

    #[test]
    fn capability_digest_binds_the_actual_operation_and_path_grant() {
        let base = ScopedGrantWire {
            operations: vec!["document.resolve".to_owned()],
            capabilities: Vec::new(),
            paths: vec![GrantPathWire::Subtree {
                path: "ae-sdd-doc/Story".to_owned(),
            }],
        };
        let wider_operation = ScopedGrantWire {
            operations: vec!["document.resolve".to_owned(), "document.save".to_owned()],
            ..base.clone()
        };
        let wider_path = ScopedGrantWire {
            paths: vec![GrantPathWire::ProjectRoot],
            ..base.clone()
        };
        let digest = capability_grant_digest(
            "workspace",
            "session",
            WireAgentRole::Task,
            Some("delegation"),
            &base,
            "policy",
            "hook.engaged",
        )
        .expect("digest");
        assert_ne!(
            digest,
            capability_grant_digest(
                "workspace",
                "session",
                WireAgentRole::Task,
                Some("delegation"),
                &wider_operation,
                "policy",
                "hook.engaged",
            )
            .expect("digest")
        );
        assert_ne!(
            digest,
            capability_grant_digest(
                "workspace",
                "session",
                WireAgentRole::Task,
                Some("delegation"),
                &wider_path,
                "policy",
                "hook.engaged",
            )
            .expect("digest")
        );
    }
}
