[package]
name = "ae-sdd-policy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ae-sdd-domain = { path = "../ae-sdd-domain" }

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
