//! Bounded parsing for source-SKILL frontmatter.
//!
//! Source-SKILL files use a deliberately small YAML subset. The build tool
//! needs only scalar metadata and must preserve all non-generated source text,
//! so this parser rejects ambiguous maps instead of accepting a permissive
//! last-key-wins interpretation.

use std::collections::{BTreeMap, BTreeSet};

const MAX_FRONTMATTER_BYTES: usize = 128 * 1024;
const MAX_FRONTMATTER_LINES: usize = 2_048;
const GENERATED_SOURCE_FIELDS: [&str; 9] = [
    "source_slimmed",
    "source_slim_schema",
    "source_slim_standard",
    "source_slim_template",
    "source_fallback",
    "source_fallback_sha256",
    "source_original_bytes",
    "source_original_lines",
    "source_semantic_inventory_sha256",
];

#[derive(Clone, Debug)]
pub(crate) struct Frontmatter {
    pub(crate) body: String,
    pub(crate) metadata: BTreeMap<String, String>,
    entries: Vec<FrontmatterEntry>,
}

#[derive(Clone, Debug)]
struct FrontmatterEntry {
    key: Option<String>,
    leading_trivia: String,
    raw: String,
}

/// Converts source text into the byte representation used for hashes and
/// generated entries.
pub(crate) fn normalize_text(text: &str) -> String {
    let normalized = text.replace("\r\n", "\n").replace('\r', "\n");
    normalized
        .strip_prefix('\u{feff}')
        .unwrap_or(&normalized)
        .to_owned()
}

/// Parses one bounded frontmatter block. A None result means that the source
/// has no opening and closing frontmatter delimiters.
pub(crate) fn parse_frontmatter(text: &str) -> Result<Option<Frontmatter>, String> {
    let Some((raw, body)) = split_frontmatter(text) else {
        return Ok(None);
    };
    if raw.len() > MAX_FRONTMATTER_BYTES {
        return Err(format!("frontmatter exceeds {MAX_FRONTMATTER_BYTES} bytes"));
    }

    let lines = raw.split('\n').collect::<Vec<_>>();
    if lines.len() > MAX_FRONTMATTER_LINES {
        return Err(format!("frontmatter exceeds {MAX_FRONTMATTER_LINES} lines"));
    }

    let mut entries = Vec::new();
    let mut metadata = BTreeMap::new();
    let mut seen = BTreeSet::new();
    let mut trivia = String::new();
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index];
        if line.is_empty() || line.starts_with('#') {
            append_line(&mut trivia, line);
            index += 1;
            continue;
        }
        if line.starts_with([' ', '\t']) {
            return Err(format!("unexpected indented line at {}", index + 1));
        }
        let (key, value) = split_key_value(line)
            .ok_or_else(|| format!("invalid frontmatter field at line {}", index + 1))?;
        if !is_valid_key(key) {
            return Err(format!("invalid frontmatter key {key:?}"));
        }
        if !seen.insert(key.to_owned()) {
            return Err(format!("duplicate frontmatter key {key:?}"));
        }

        let entry_start = index;
        index += 1;
        let parsed_value = if is_block_scalar(value) {
            let continuation_start = index;
            while index < lines.len() && is_indented_or_blank(lines[index]) {
                index += 1;
            }
            parse_block_scalar(value, &lines[continuation_start..index])?
        } else if value.trim().is_empty() {
            let continuation_start = index;
            while index < lines.len() && is_indented_or_blank(lines[index]) {
                index += 1;
            }
            parse_empty_value(key, &lines[continuation_start..index])?
        } else {
            if index < lines.len() && lines[index].starts_with([' ', '\t']) {
                return Err(format!(
                    "scalar frontmatter field {key:?} has an indented continuation"
                ));
            }
            parse_scalar(value)?
        };
        metadata.insert(key.to_owned(), parsed_value);

        let leading_trivia = std::mem::take(&mut trivia);
        let mut entry_raw = String::new();
        for source_line in &lines[entry_start..index] {
            append_line(&mut entry_raw, source_line);
        }
        entries.push(FrontmatterEntry {
            key: Some(key.to_owned()),
            leading_trivia,
            raw: entry_raw,
        });
    }
    if !trivia.is_empty() {
        entries.push(FrontmatterEntry {
            key: None,
            leading_trivia: String::new(),
            raw: trivia,
        });
    }

    Ok(Some(Frontmatter {
        body: body.to_owned(),
        metadata,
        entries,
    }))
}

/// Produces the original frontmatter while removing only fields generated by
/// source-slim. User-defined source-prefixed metadata remains semantic input.
pub(crate) fn clean_frontmatter(frontmatter: &Frontmatter) -> String {
    let mut rendered = String::new();
    for entry in &frontmatter.entries {
        // A comment block precedes the field rather than belonging to it, so
        // it remains even when the following field is generated.
        rendered.push_str(&entry.leading_trivia);
        let generated = entry
            .key
            .as_deref()
            .is_some_and(|key| GENERATED_SOURCE_FIELDS.contains(&key));
        if !generated {
            rendered.push_str(&entry.raw);
        }
    }
    while rendered.ends_with('\n') {
        rendered.pop();
    }
    rendered
}

/// Returns whether a parsed metadata field uses the canonical true literal.
pub(crate) fn is_true(value: Option<&String>) -> bool {
    value.is_some_and(|value| matches!(value.as_str(), "true" | "True" | "TRUE"))
}

fn split_frontmatter(text: &str) -> Option<(&str, &str)> {
    let mut fragments = text.split_inclusive('\n');
    let first = fragments.next()?;
    if delimiter(first) != "---" {
        return None;
    }

    let first_end = first.len();
    let mut offset = first_end;
    for fragment in fragments {
        let start = offset;
        offset += fragment.len();
        if delimiter(fragment) == "---" {
            return Some((&text[first_end..start], &text[offset..]));
        }
    }
    None
}

fn delimiter(line: &str) -> &str {
    line.strip_suffix('\n').unwrap_or(line).trim_end()
}

fn split_key_value(line: &str) -> Option<(&str, &str)> {
    let (key, value) = line.split_once(':')?;
    Some((key.trim(), value.trim()))
}

fn is_valid_key(key: &str) -> bool {
    !key.is_empty()
        && key.len() <= 128
        && key
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
}

fn is_indented_or_blank(line: &str) -> bool {
    line.is_empty() || line.starts_with(' ')
}

fn is_block_scalar(value: &str) -> bool {
    matches!(value, "|" | "|-" | "|+" | ">" | ">-" | ">+")
}

fn parse_block_scalar(indicator: &str, lines: &[&str]) -> Result<String, String> {
    if lines.iter().any(|line| line.starts_with('\t')) {
        return Err("frontmatter block scalar cannot use tabs".to_owned());
    }
    let common_indent = lines
        .iter()
        .filter(|line| !line.is_empty())
        .map(|line| line.len() - line.trim_start_matches(' ').len())
        .min()
        .unwrap_or(0);
    let values = lines
        .iter()
        .map(|line| line.get(common_indent..).unwrap_or(line))
        .collect::<Vec<_>>();
    let value = if indicator.starts_with('>') {
        values.join(" ").trim().to_owned()
    } else {
        values.join("\n").trim().to_owned()
    };
    Ok(value)
}

fn parse_empty_value(key: &str, lines: &[&str]) -> Result<String, String> {
    if lines.iter().all(|line| line.is_empty()) {
        return Ok(String::new());
    }

    let common_indent = lines
        .iter()
        .filter(|line| !line.is_empty())
        .map(|line| line.len() - line.trim_start_matches(' ').len())
        .min()
        .unwrap_or(0);
    let mut values = Vec::new();
    for line in lines {
        if line.is_empty() {
            continue;
        }
        let indent = line.len() - line.trim_start_matches(' ').len();
        if indent != common_indent {
            return Err(format!(
                "nested frontmatter collection is unsupported for {key:?}"
            ));
        }
        let item = line
            .get(common_indent..)
            .and_then(|value| value.strip_prefix('-'))
            .and_then(|value| value.strip_prefix(' '))
            .ok_or_else(|| {
                format!(
                    "nested frontmatter mapping is unsupported for {key:?}; only flat string lists are accepted"
                )
            })?;
        let value = parse_scalar(item)?;
        if value.is_empty() {
            return Err(format!("empty list item is unsupported for {key:?}"));
        }
        values.push(value);
    }
    if values.is_empty() {
        return Err(format!(
            "empty frontmatter collection is unsupported for {key:?}"
        ));
    }
    Ok(values.join(", "))
}

fn parse_scalar(value: &str) -> Result<String, String> {
    let value = strip_inline_comment(value).trim();
    if value.starts_with('"') || value.starts_with('\'') {
        let quote = value.chars().next().expect("checked non-empty");
        if value.len() < 2 || !value.ends_with(quote) {
            return Err("unterminated quoted frontmatter scalar".to_owned());
        }
        return Ok(value[1..value.len() - 1].to_owned());
    }
    if value.starts_with(['[', '{', '&', '*', '!']) {
        return Err(
            "flow collections, aliases, and tags are unsupported in frontmatter".to_owned(),
        );
    }
    if value.contains('\t') || value.contains('\0') {
        return Err("invalid control character in frontmatter scalar".to_owned());
    }
    Ok(value.to_owned())
}

fn strip_inline_comment(value: &str) -> &str {
    let mut quote = None;
    let mut escaped = false;
    let mut previous_was_whitespace = true;
    for (index, character) in value.char_indices() {
        if let Some(active_quote) = quote {
            if active_quote == '"' && character == '\\' && !escaped {
                escaped = true;
                continue;
            }
            if character == active_quote && !escaped {
                quote = None;
            }
            escaped = false;
        } else if matches!(character, '"' | '\'') {
            quote = Some(character);
        } else if character == '#' && previous_was_whitespace {
            return value[..index].trim_end();
        }
        previous_was_whitespace = character.is_whitespace();
    }
    value.trim_end()
}

fn append_line(target: &mut String, line: &str) {
    target.push_str(line);
    target.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_block_scalars_and_preserves_non_generated_source_metadata() {
        let text = "---\nname: example\ndescription: |\n  one\n  two\nsource_identity: durable\nsource_fallback: old.md\n---\n\n# Heading\n";
        let frontmatter = parse_frontmatter(text)
            .expect("frontmatter parses")
            .expect("frontmatter exists");
        assert_eq!(frontmatter.metadata["description"], "one\ntwo");
        assert_eq!(
            clean_frontmatter(&frontmatter),
            "name: example\ndescription: |\n  one\n  two\nsource_identity: durable"
        );
    }

    #[test]
    fn rejects_duplicate_keys_instead_of_overwriting_them() {
        let text = "---\nname: first\nname: second\n---\n";
        let error = parse_frontmatter(text).expect_err("duplicate key is invalid");
        assert!(error.contains("duplicate"));
    }

    #[test]
    fn parses_flat_string_lists_and_preserves_their_raw_frontmatter() {
        let text =
            "---\nname: example\nallowed_tools:\n  - \"ae-sdd\" # native CLI\n  - Bash\n---\n";
        let frontmatter = parse_frontmatter(text)
            .expect("frontmatter parses")
            .expect("frontmatter exists");

        assert_eq!(frontmatter.metadata["allowed_tools"], "ae-sdd, Bash");
        assert!(clean_frontmatter(&frontmatter).contains("allowed_tools:\n  - \"ae-sdd\""));
    }

    #[test]
    fn cleaning_generated_fields_preserves_their_leading_comments() {
        let text = "---\nname: example\n# Retain this source comment.\nsource_fallback: legacy.md\ndescription: durable\n---\n";
        let frontmatter = parse_frontmatter(text)
            .expect("frontmatter parses")
            .expect("frontmatter exists");

        assert_eq!(
            clean_frontmatter(&frontmatter),
            "name: example\n# Retain this source comment.\ndescription: durable"
        );
    }

    #[test]
    fn rejects_nested_mappings_instead_of_silently_dropping_them() {
        let text = "---\nname: example\nlimits:\n  maximum: 2\n---\n";
        let error = parse_frontmatter(text).expect_err("nested mapping is unsupported");
        assert!(error.contains("nested frontmatter mapping"));
    }
}
