package com.example.loan.domain;

public enum DecisionReason {
    APPROVED_PRIME,
    APPROVED_STANDARD,
    UNDERAGE,
    OVER_AGE_LIMIT,
    FRAUD_FLAGGED,
    UNEMPLOYED,
    INSUFFICIENT_INCOME,
    HIGH_DTI,
    LOW_CREDIT_SCORE,
    AMOUNT_EXCEEDS_LIMIT,
    EMPLOYMENT_VERIFICATION_FAILED,
    CREDIT_BUREAU_UNAVAILABLE
}
