#[cfg(feature = "client")]
pub mod access;
#[cfg(feature = "service")]
pub mod audit;
#[cfg(feature = "service")]
pub mod cache;
#[cfg(feature = "client")]
pub mod client_config;
pub mod config;
#[cfg(feature = "admin")]
pub mod management;
#[cfg(feature = "service")]
pub mod daemon;
#[cfg(feature = "service")]
pub mod database;
#[cfg(feature = "client")]
pub mod ipc;
#[cfg(feature = "service")]
pub mod lifecycle;
#[cfg(feature = "client")]
pub mod protocol;
#[cfg(feature = "service")]
pub mod query_guard;
#[cfg(feature = "service")]
pub mod registry;
#[cfg(feature = "client")]
pub mod routing;
#[cfg(feature = "service")]
pub mod security;
#[cfg(feature = "service")]
pub mod sql_policy;
#[cfg(feature = "service")]
pub mod vault;
